# Generated by Django 5.2.4 on 2025-11-03 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('alimento', 'Alimento'), ('higiene', 'Higiene'), ('roupa', 'Roupa'), ('outros', 'Outros')], max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
