# Generated by Django 5.2.4 on 2025-12-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_pedidoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='visivel_para_doador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='doacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.doacao'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
